#!/bin/sh

set -e

proj_version="$1"

if [ "$proj_version" == "" ]; then
  echo "usage: $0 VERSION"
  exit 1
fi

if [ "$AWS_ID" == "" ]; then
  echo "must set AWS_ID"
  exit 1
fi

if [ "$AWS_SECRET" == "" ]; then
  echo "must set AWS_SECRET"
  exit 1
fi

if [ "$S3_BUCKET" == "" ]; then
  echo "must set S3_BUCKET"
  exit 1
fi

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

# make a temp directory
tempdir="$( mktemp -t proj_$proj_version )"
rm -rf $tempdir
mkdir -p $tempdir
cd $tempdir

# build and package proj for heroku
vulcan build -v \
  -n proj \
  -c "cd proj-${proj_version} && ./configure --prefix=/app/vendor/proj && make && make install" \
  -p /app/vendor/proj \
  -s http://download.osgeo.org/proj/proj-${proj_version}.tar.gz \
  -o $tempdir/proj-${proj_version}.tgz

# upload proj to s3
$basedir/aws/s3 put $S3_BUCKET \
  proj-${proj_version}.tgz $tempdir/proj-${proj_version}.tgz

# generate manifest
$basedir/manifest proj
